data:
  save_dir: "runs/default/"
  tomo0_files: []
  tomo1_files: []
  # Optional there is an inbuilt mask generator as well
  mask_file: null
   # Option 1: use tilt_min and tilt_max
  #tilt_max: 57.1
  #tilt_min: -60.0
  # Option 2: use angle_file instead (comment above lines)
  angle_file: null


train_params:
  device: 0 # eg. 0, 1, 2 for GPU or -1 for CPU or "cuda:0", "cuda:1"  and 'cpu' for CPU
  input_crop_size: 72
  iterations: 50000
  scale: 2.0
  batch_size: 8 # Change this if doesnt fit in memory
  seed: 42
  compile: false # speed up training(but will take some time initially to compile and throws lots of warnings)
  use_fourier: false
  use_spherical_support: true
  wedge_low_support: 0
  ref_wedge_support: 1
  wedge_double_size: true
  save_n_iterations: 5000
  compute_avg_loss_n_iterations: 1000
  use_flips: true
  normalize_crops: false
  use_inp_wedge: false
  learning_rate: 1e-4
  use_mixed_precision: true
  no_window: false
  view_as_real: true
  upsample_volume: false
  eq_use_direct: false
  min_distance: 0.5 # related to choosing the different rotations of the volume 
  window_type: "boxcar"

predict_params:
  batch_size: 5
  stride: 36
  pre_pad: true
  pre_pad_size: null
  avg_pool: false

model_params:
  name: "unet3d_bf"
  num_levels: 4
  upsample: "default"
  layer_order: "cr"
  use_bias: false
  padding_mode: "zeros"
  pool_type: "max"
  dropout_prob: 0.1
# model_params:
#   name: "iso_unet3d"

mask_params:
  use_mask: true
  mask_frac: 0.5


pretrain_params:
  use_pretrain: false
  model_path: None